/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.avinam.gui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import lk.avinam.panel.DoctorDashboardAppointment;
import lk.avinam.panel.DoctorDashboardPanel;
import lk.avinam.panel.DoctorManagementPanel;

/**
 *
 * @author Inaamul Hasan
 */
public class DoctorDashboard extends javax.swing.JFrame {

    private DoctorDashboardPanel dashboardPanel;
    private DoctorDashboardAppointment appointmentPanel;

    private CardLayout contentPanelLayout;

    /**
     * Creates new form Dashboard
     */
    public DoctorDashboard() {
        initComponents();
        init();
        loadPanels();
    }

    private void init() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    private void loadPanels() {
        if (contentPanelLayout == null && contentPanel.getLayout() instanceof CardLayout) {
            this.contentPanelLayout = (CardLayout) contentPanel.getLayout();    
        } 
       
        this.dashboardPanel = new DoctorDashboardPanel();   
        this.contentPanel.add(dashboardPanel,"dashboard_panel");
        
        this.appointmentPanel = new DoctorDashboardAppointment();   
        this.contentPanel.add(appointmentPanel,"appointment_panel");
        SwingUtilities.updateComponentTreeUI(contentPanel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        doctorDashboardBtn = new javax.swing.JButton();
        doctorManagementBtn = new javax.swing.JButton();
        doctorManagementBtn1 = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(3, 4, 94));

        doctorDashboardBtn.setBackground(new java.awt.Color(202, 240, 248));
        doctorDashboardBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        doctorDashboardBtn.setForeground(new java.awt.Color(3, 4, 94));
        doctorDashboardBtn.setText("Dashboard");
        doctorDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doctorDashboardBtn.setMargin(new java.awt.Insets(2, 5, 3, 14));
        doctorDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorDashboardBtnActionPerformed(evt);
            }
        });

        doctorManagementBtn.setBackground(new java.awt.Color(202, 240, 248));
        doctorManagementBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        doctorManagementBtn.setForeground(new java.awt.Color(3, 4, 94));
        doctorManagementBtn.setText("Manage Appointments");
        doctorManagementBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doctorManagementBtn.setMargin(new java.awt.Insets(2, 5, 3, 14));
        doctorManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorManagementBtnActionPerformed(evt);
            }
        });

        doctorManagementBtn1.setBackground(new java.awt.Color(202, 240, 248));
        doctorManagementBtn1.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        doctorManagementBtn1.setForeground(new java.awt.Color(3, 4, 94));
        doctorManagementBtn1.setText("Log Out");
        doctorManagementBtn1.setMargin(new java.awt.Insets(2, 5, 3, 14));
        doctorManagementBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorManagementBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorManagementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(doctorDashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorManagementBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(doctorDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorManagementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doctorManagementBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        headerPanel.setBackground(new java.awt.Color(3, 4, 94));

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 240, 248));
        jLabel1.setText("Doctor Dashboard");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contentPanel.setBackground(new java.awt.Color(202, 240, 248));
        contentPanel.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorDashboardBtnActionPerformed
        // TODO add your handling code here:
this.contentPanelLayout.show(contentPanel, "dashboard_panel");
    }//GEN-LAST:event_doctorDashboardBtnActionPerformed

    private void doctorManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorManagementBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel, "appointment_panel");
    }//GEN-LAST:event_doctorManagementBtnActionPerformed

    private void doctorManagementBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorManagementBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorManagementBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton doctorDashboardBtn;
    private javax.swing.JButton doctorManagementBtn;
    private javax.swing.JButton doctorManagementBtn1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
