/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.avinam.gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import lk.avinam.panel.Medicine;
import lk.avinam.panel.MedicineSales;
import lk.avinam.panel.MedicineStock;
import lk.avinam.panel.PharmacistDashboardPanel;
import lk.avinam.panel.SupplierList;
import lk.avinam.util.AppIconUtil;

/**
 *
 * @author Inaamul Hasan
 */
public class PharmacistDashboard extends javax.swing.JFrame {

    private PharmacistDashboardPanel pharmaDashboardPanel;
    private Medicine medicineListPanel;
    private MedicineSales medicineSales;
    private SupplierList supplierList;
    private MedicineStock medicineStock;
    private CardLayout contentPanelLayout;
    

    /**
     * Creates new form Dashboard
     */
    public PharmacistDashboard() {
        initComponents();
        init();
        loadPanels();
    }

    private void init() {
        AppIconUtil.applyIcon(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        FlatSVGIcon dashboardIcon = new FlatSVGIcon("lk/avinam/icon/dashboard.svg", 20, 20);
        dashboardIcon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Color.decode("#03045E")));
        pharmaDashboardBtn.setIcon(dashboardIcon);
        
        FlatSVGIcon medicineListIcon = new FlatSVGIcon("lk/avinam/icon/medicine-list.svg", 25, 25);
        medicineListIcon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Color.decode("#03045E")));
        medicineListBtn.setIcon(medicineListIcon);
        
        FlatSVGIcon medicineSalesIcon = new FlatSVGIcon("lk/avinam/icon/sales.svg", 20, 20);
        medicineSalesIcon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Color.decode("#03045E")));
        medicineSalesBtn.setIcon(medicineSalesIcon);
        
        FlatSVGIcon supplierIcon = new FlatSVGIcon("lk/avinam/icon/package.svg", 20, 20);
        supplierIcon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Color.decode("#03045E")));
        supplierBtn.setIcon(supplierIcon);
        
        FlatSVGIcon logOutIcon = new FlatSVGIcon("lk/avinam/icon/log-out.svg", 20, 20);
        logOutIcon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Color.decode("#03045E")));
        logOutBtn.setIcon(logOutIcon);
        
        FlatSVGIcon medicineStockIcon = new FlatSVGIcon("lk/avinam/icon/stocks.svg", 20, 20);
        medicineStockIcon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Color.decode("#03045E")));
        medicineStockBtn.setIcon(medicineStockIcon);
        
       
    }

    private void loadPanels() {
        if (contentPanelLayout == null && contentPanel.getLayout() instanceof CardLayout) {
            this.contentPanelLayout = (CardLayout) contentPanel.getLayout();
        }
        this.pharmaDashboardPanel = new PharmacistDashboardPanel();
        this.contentPanel.add(pharmaDashboardPanel, "dashboard_panel");
        
        this.medicineListPanel = new Medicine();
        this.contentPanel.add(medicineListPanel, "medicine_panel");
        
        this.medicineSales = new MedicineSales();
        this.contentPanel.add(medicineSales, "sales_panel");
        
        this.supplierList = new SupplierList();
        this.contentPanel.add(supplierList, "supplier_panel");
        
        this.medicineStock = new MedicineStock();
        this.contentPanel.add(medicineStock, "medicineStock_panel");

        SwingUtilities.updateComponentTreeUI(contentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        pharmaDashboardBtn = new javax.swing.JButton();
        medicineListBtn = new javax.swing.JButton();
        medicineSalesBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        medicineStockBtn = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(3, 4, 94));

        pharmaDashboardBtn.setBackground(new java.awt.Color(144, 224, 239));
        pharmaDashboardBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        pharmaDashboardBtn.setForeground(new java.awt.Color(3, 4, 94));
        pharmaDashboardBtn.setText(" Dashboard");
        pharmaDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pharmaDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmaDashboardBtnActionPerformed(evt);
            }
        });

        medicineListBtn.setBackground(new java.awt.Color(144, 224, 239));
        medicineListBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        medicineListBtn.setForeground(new java.awt.Color(3, 4, 94));
        medicineListBtn.setText(" Medicine List");
        medicineListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medicineListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineListBtnActionPerformed(evt);
            }
        });

        medicineSalesBtn.setBackground(new java.awt.Color(144, 224, 239));
        medicineSalesBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        medicineSalesBtn.setForeground(new java.awt.Color(3, 4, 94));
        medicineSalesBtn.setText(" Medicine Sales List");
        medicineSalesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medicineSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineSalesBtnActionPerformed(evt);
            }
        });

        supplierBtn.setBackground(new java.awt.Color(144, 224, 239));
        supplierBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        supplierBtn.setForeground(new java.awt.Color(3, 4, 94));
        supplierBtn.setText(" Supplier List");
        supplierBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(144, 224, 239));
        logOutBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(3, 4, 94));
        logOutBtn.setText("Log Out");

        medicineStockBtn.setBackground(new java.awt.Color(144, 224, 239));
        medicineStockBtn.setFont(new java.awt.Font("Nunito ExtraBold", 1, 14)); // NOI18N
        medicineStockBtn.setForeground(new java.awt.Color(3, 4, 94));
        medicineStockBtn.setText(" Medicine Stock");
        medicineStockBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medicineStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineStockBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicineListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicineSalesBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(supplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(medicineStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pharmaDashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(medicineListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicineSalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicineStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuPanelLayout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(pharmaDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );

        headerPanel.setBackground(new java.awt.Color(3, 4, 94));

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 240, 248));
        jLabel1.setText("Pharmacist Dashboard");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(202, 240, 248));
        contentPanel.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pharmaDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmaDashboardBtnActionPerformed
        // TODO add your handling code here:

      this.contentPanelLayout.show(contentPanel, "dashboard_panel");
    }//GEN-LAST:event_pharmaDashboardBtnActionPerformed

    private void medicineListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineListBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel, "medicine_panel");
    }//GEN-LAST:event_medicineListBtnActionPerformed

    private void medicineSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineSalesBtnActionPerformed
        // TODO add your handling code here:
        
        this.contentPanelLayout.show(contentPanel, "sales_panel");
    }//GEN-LAST:event_medicineSalesBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel, "supplier_panel");
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void medicineStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineStockBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel, "medicineStock_panel");
    }//GEN-LAST:event_medicineStockBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacistDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton medicineListBtn;
    private javax.swing.JButton medicineSalesBtn;
    private javax.swing.JButton medicineStockBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton pharmaDashboardBtn;
    private javax.swing.JButton supplierBtn;
    // End of variables declaration//GEN-END:variables
}
